image:
  repository: ghcr.io/baruchihalamish20/user-service
  tag: "e365890"
env:
  - name: SECRET_KEY
    value: "dev-secret-user"
  - name: APP_ENV
    value: "dev"
service:
  type: LoadBalancer
  port: 80
  nodePort: 30011