image:
  repository: ghcr.io/omermaman1411-ctrl/order-service
  tag: "latest"
replicaCount: 1

service:
  # NodePort for Docker Desktop, LoadBalancer for cloud
  type: LoadBalancer
  port: 80
  nodePort: 30002

env:
  - name: SECRET_KEY
    value: "change-me"
