image:
  repository: ghcr.io/baruchihalamish20/user-service
  tag: "latest"
replicaCount: 1

service:
  # NodePort for Docker Desktop, LoadBalancer for cloud
  type: NodePort
  port: 80
  nodePort: 50001

env:
  - name: SECRET_KEY
    value: "change-me"
